- hosts: workers
  tasks:
    - name: Distribute Key
      copy:
        src: /home/{{ansible_user_id}}/.ssh/id_rsa
        dest: /home/{{ansible_user_id}}/.ssh 
        mode: 0600

    - name: Copy known_hosts to workers
      copy:
       src: /home/{{ansible_user_id}}/.ssh/known_hosts
       dest: /home/{{ansible_user_id}}/.ssh
       mode: 0644
